out_dir: ./results/Cora/
metric_agg: argmax
metric_best: accuracy
seed: 0
dataset:
  dir: /mnt/data2/duxin/.datasets
  format: PyG-Planetoid
  name: cora
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: 
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  sampler: full_batch
gnn:
  mode: "off"
  layer_type: GCN
  act: gelu
  agg: mean
  batchnorm: true
  dim_inner: 96
  dropout: 0.2
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false

gt:
  attn_dropout: 0.5
  batch_norm: false
  dim_hidden: 96
  dropout: 0.5
  layer_norm: true
  layer_type: Transformer
  attn_type: GeneralAttention
  layers: 3
  n_heads: 1
  ffn_dim: 192
  head: node
  node_encoder_list: [RawEncoder,LapPE]
  edge_encoder_list: [DummyEdge]

model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: GTModel
optim:
  base_lr: 0.0005
  clip_grad_norm: true
  max_epoch: 300
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 1e-5

posenc_GraphormerBias:
  enable: false
  node_degrees_only: true
  num_in_degrees: 729
  num_out_degrees: 89
  num_spatial_types: 20
posenc_LapPE:
  dim_pe: 4
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 4
  enable: true
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
perf:
  mode: full
  include_name: ["FullMask","RawNodeEncoder","LapPENodeEncoder","DummyEdgeEncoder","GeneralAttn","FFN_block","GNNNodeHead"]
