out_dir: ./results/arxiv/
metric_agg: argmax
metric_best: accuracy
num_workers: 0
seed: 442
# device: cuda:1
dataset:
  dir: /mnt/data2/duxin/.datasets/
  format: OGB
  name: ogbn-arxiv
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
  add_self_loops: True

train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  batch_size: 256
  tqdm: false
  sampler: neighbor
  persistent_workers: True
  pin_memory: True
  neighbor_sizes: [25,10]

val:
  sampler: neighbor
gnn:
  mode: GPS
  layer_type: GCN
  act: relu
  agg: add
  batchnorm: true
  dim_inner: 128
  dropout: 0.3
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false

gt:
  attn_dropout: 0.5
  batch_norm: true
  dim_hidden: 128
  dropout: 0.3
  layer_norm: false
  layer_type: Transformer
  attn_type: GeneralAttention
  layers: 4
  n_heads: 2
  ffn_dim: 256
  head: minibatch_node
  encoder_type : cascade
  node_encoder_list: [RawEncoder,GraphormerBias]
  edge_encoder_list: [DummyEdge]

model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: GTModel
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 2
  num_warmup_epochs: 5
  optimizer: adamW
  clip_grad_norm_value: 1.0
  scheduler: cosine_with_warmup
  weight_decay: 0.001
posenc_GraphormerBias:
  enable: true
  node_degrees_only: true
  num_spatial_types: 20
  use_graph_token: false
posenc_LapPE:
  dim_pe: 4
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 4
  enable: false
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
perf:
  mode: "full"