out_dir: ./results/arxiv/
metric_agg: argmax
metric_best: accuracy
num_workers: 0
seed: 42
# device: cuda:1
dataset:
  dir: /mnt/data2/duxin/.datasets
  format: OGB
  name: ogbn-arxiv
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
  add_self_loops: True
metis:
  patches: 3000
train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  batch_size: 256
  tqdm: false
  sampler: cluster
  persistent_workers: True
  pin_memory: True
  neighbor_sizes: [25,10]
val:
  sampler: cluster
gnn:
  mode: GPS
  layer_type: GAT
  act: relu
  agg: add
  batchnorm: true
  dim_inner: 128
  dropout: 0.3
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false

gt:
  attn_dropout: 0.2
  batch_norm: false
  dim_hidden: 256
  dropout: 0.5
  residual: true 
  layer_norm: true
  layer_type: Transformer
  attn_type: GeneralAttention
  layers: 4
  attn_heads: 8
  ffn_dim: 1024
  head: node
  encoder_type : cascade
  node_encoder_list: [RawEncoder]
  edge_encoder_list: [DummyEdge]

model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: GTModel
optim:
  base_lr: 0.005
  clip_grad_norm: true
  max_epoch: 500
  num_warmup_epochs: 5
  optimizer: adamW
  clip_grad_norm_value: 0.5
  scheduler: cosine_with_warmup
  weight_decay: 5e-4
posenc_GraphormerBias:
  enable: false
  node_degrees_only: true
  num_spatial_types: 20
  use_graph_token: false
posenc_LapPE:
  dim_pe: 4
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 4
  enable: false
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
perf:
  mode: "off"