out_dir: ./results/test/
metric_agg: argmax
metric_best: accuracy
seed: 42
num_workers: 0
dataset:
  format: OGB
  name: ogbn-products
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
  add_self_loops: true
metis:
  drop_rate: 0.0
  enable: true
  num_hops: 0
  online: true
  patch_num_diff: -1
  patch_rw_dim: 0
  patches: 8192
  mode: subgraph
gnn:
  act: relu
  agg: mean
  batch_norm: true
  dim_inner: 256
  layers : 3
  dropout: 0.
  head: node
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false
gt:
  aggregate: add
  attn_dropout: 0.5
  batch_norm: false
  dim_hidden: 256
  dropout: 0.5
  graph_weight: 0.5
  layer_norm: true
  layer_type: GCN+Transformer
  layers: 1
  n_heads: 1
  use_act: true
  use_graph: true
  use_residual: true
  use_weight: true
model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: SGFormer
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 400
  num_warmup_epochs: 20
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.
posenc_GraphormerBias:
  enable: false
  node_degrees_only: true
  num_in_degrees: 729
  num_out_degrees: 89
  num_spatial_types: 20
posenc_LapPE:
  dim_pe: 4
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 4
  enable: false
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
posenc_RWSE:
  dim_pe: 16
  enable: false
  kernel:
    times_func: range(1,17)
  model: Linear
  raw_norm_type: BatchNorm
train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  batch_size: 256
  tqdm: True
  sampler: full_batch
  persistent_workers: True
  pin_memory: True
perf:
  mode: "op-only"
