out_dir: ./results/test/
metric_agg: argmax
metric_best: accuracy
num_workers: 1
seed: 0
dataset:
  dir: /mnt/data2/duxin/.datasets
  format: OGB
  name: ogbn-arxiv
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
  preprocess: Expand
  exp_algorithm: Random-d
  exp_count: 1
  exp_deg: 3
  exp_max_num_iters: 100
  num_virt_node: 0
  add_self_loops: True
train:
  enable_ckpt: false
  eval_period: 1
  mode: custom
  batch_size: 1
  sampler: full_batch
  ckpt_period: 100
gnn:
  mode: GPS
  layer_type: GCN
  act: relu
  agg: add
  batch_norm: true
  dim_inner: 80
  dropout: 0.3
  layers_post_mp: 1
  layers_pre_mp: 1
  normalize_adj: false

gt:
  attn_dropout: 0.5
  act: relu
  batch_norm: true
  dim_hidden: 80
  dropout: 0.3
  layer_norm: false
  layer_type: Exphormer
  attn_type: ExphormerAttention
  layers: 4
  n_heads: 2
  ffn_dim: 160
  head: node
  encoder_type : cascade
  node_encoder_list: [RawEncoder]
  edge_encoder_list: [DummyEdge,Edgefixer]

model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: GTModel
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 200
  num_warmup_epochs: 5
  optimizer: adamW
  clip_grad_norm_value: 1.0
  scheduler: cosine_with_warmup
  weight_decay: 0.001
perf:
  mode: "full"
reorder_Metis:
  enable: false
  block_size: 128
reorder_RCM:
  enable: false
reorder_Slashburn:
  enable: false
  block_size: 128
reorder_Random:
  enable: false
  block_size: 128
reorder_BFS:
  enable: false
  block_size: 128
reorder_Degree:
  enable: false
  block_size: 128
reorder_GOrder:
  enable: false
  block_size: 128