out_dir: ./results/test/
metric_agg: argmax
metric_best: accuracy
seed: 0
num_workers: 0
dataset:
  format: PyG-Planetoid
  name: cora
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: LinearNode+LapPE+RWSE
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
gnn:
  act: gelu
  agg: mean
  batch_norm: true
  dim_inner: 80
  dropout: 0.2
  head: node
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false
gt:
  K: 2
  attn_dropout: 0.5
  batch_norm: false
  dim_hidden: 80
  dropout: 0.2
  layer_norm: true
  layer_type: GCN+Transformer
  layers: 2
  n_heads: 2
  # encoder_type : cascade
  node_encoder_list: [RawEncoder,LapPE,RWSE]
  edge_encoder_list: []
model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: DeGTA
optim:
  base_lr: 0.0005
  clip_grad_norm: true
  max_epoch: 400
  num_warmup_epochs: 20
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 5e-4
posenc_GraphormerBias:
  enable: false
  node_degrees_only: true
  num_in_degrees: 729
  num_out_degrees: 89
  num_spatial_types: 20
posenc_LapPE:
  dim_pe: 8
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 4
  enable: true
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
posenc_RWSE:
  dim_pe: 8
  enable: true
  kernel:
    times_func: range(1,17)
  model: Linear
  raw_norm_type: BatchNorm
train:
  enable_ckpt: false
  eval_period: 1
  mode: custom
  sampler: full_batch
